# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-25 15:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0005_car'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('sheng', models.CharField(max_length=100)),
                ('shi', models.CharField(max_length=100)),
                ('xian', models.CharField(max_length=100)),
                ('addinfo', models.CharField(max_length=255)),
                ('isselect', models.IntegerField(default=0)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.Users')),
            ],
        ),
        migrations.CreateModel(
            name='Citys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level', models.IntegerField()),
                ('upid', models.IntegerField()),
            ],
            options={
                'db_table': 'citys',
            },
        ),
    ]
