# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-11 17:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0007_order_orderinfo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'permissions': (('show_address', '查看地址管理'), ('insert_address', '添加地址'), ('edit_address', '修改地址'), ('del_address', '删除地址'))},
        ),
        migrations.AlterModelOptions(
            name='cates',
            options={'permissions': (('show_cates', '查看商品分类管理'), ('insert_cates', '添加商品分类'), ('edit_cates', '修改商品分类'), ('del_cates', '删除商品分类'))},
        ),
        migrations.AlterModelOptions(
            name='goods',
            options={'permissions': (('show_goods', '查看商品管理'), ('insert_goods', '添加商品'), ('edit_goods', '修改商品'), ('del_goods', '删除商品'))},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'permissions': (('show_order', '查看订单管理'), ('insert_order', '添加订单'), ('edit_order', '修改订单'), ('del_order', '删除订单'))},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'permissions': (('show_users', '查看会员管理'), ('insert_users', '添加会员'), ('edit_users', '修改会员'), ('del_users', '删除会员'))},
        ),
    ]
